import { Button, VerticalBox, GridBox, ComboBox, TextEdit, ScrollView, LineEdit, GroupBox, HorizontalBox } from "std-widgets.slint";
import "./LupinademoRegular-X3ovd.otf";
import "./Aquire-BW0ox.otf";

export enum AppState {
    Select,
    Analysis
}

export component Container inherits Rectangle {
    background: #000000bb;
    border-radius: 20pt;
    drop-shadow-blur: 15pt;
    drop-shadow-color: #00000066;
}

export component SelectionScreen inherits Container {
    
}

export component AppWindow inherits Window
{
    // Callbacks
    callback open_folder_dialog() -> string;

    // Properties
    in-out property <string> selected_path: "";
    in-out property <AppState> current_state: AppState.Analysis;

    title: "Archive Manager";
    background: @linear-gradient(135deg, #0094d4 0%, #ce19c8 100%);
    min-width: 400pt;
    min-height: 280pt;
    default-font-family: "Lupina Demo";
    
    // Select Screen
    VerticalLayout {
        visible: current_state == AppState.Select;
        alignment: center;
        HorizontalLayout {
            alignment: center;
            Container {
                width: 300pt;
                VerticalLayout {
                    alignment: LayoutAlignment.stretch;
                    spacing: 10pt;
                    padding: 15pt;
            
                    Text {
                        height: 20pt;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        color: #ffffffee;
                        font-size: 15pt;
                        text: "Select Archive Device";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
            
                    HorizontalLayout {
                        height: 25pt;
                        spacing: 10pt;
            
                        ComboBox {
                            model: ["first", "second", "third"];
                        }
            
                        Button {
                            width: 60pt;
                            text: "Select";
                        }
                    }
            
                    HorizontalLayout {
                        height: 20pt;
                        spacing: 10pt;
            
                        Path {
                            commands: "M0 1H2";
                            stroke-width: 1px;
                            stroke: #ffffff66;
                        }
            
                        Text {
                            font-size: 12pt;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            color: #ffffff66;
                            text: "or";
                            vertical-alignment: TextVerticalAlignment.center;
                        }
            
                        Path {
                            commands: "M0 1H2";
                            stroke-width: 1px;
                            stroke: #ffffff66;
                        }
                    }
            
                    Text {
                        height: 20pt;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        color: #ffffffee;
                        font-size: 15pt;
                        text: "Select Archive Directory";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
            
                    HorizontalLayout {
                        height: 25pt;
                        alignment: center;
            
                        Button {
                            width: 90pt;
                            text: "Browse";
                            clicked => {
                                selected_path = root.open_folder_dialog();
                                if selected_path != ""
                                { 
                                    root.
                                    current_state = AppState.Analysis;
                                }
                            }
                        }
                    }
                }
            }

            
        }
    }
    
    // Manipulate Screen
    VerticalLayout {
        out property <int> file_count: 0;
        padding: 20pt;
        Container {
            visible: current_state == AppState.Analysis;
            VerticalLayout {
                alignment: LayoutAlignment.start;
                spacing: 10pt;
                padding: 15pt;
                Text {
                    font-family: "Aquire";
                    font-size: 25pt;
                    text: "Summary";
                }
                GridLayout {
                    height: 40pt;
                    Row {
                        Text {
                            text: "Path";
                        }
                        
                        Text {
                            horizontal-alignment: right;
                            text: "0";
                        }
                    }
                    Row {
                        Path {
                            colspan: 2;
                            commands: "M0 1H2";
                            stroke-width: 1px;
                            stroke: #ffffff66;
                        }
                    }
                    Row {
                        Text {
                            text: "File Count";
                        }
                        
                        Text {
                            horizontal-alignment: right;
                            text: "0";
                        }
                    }
                }
            }
        }
    }
}
